## 1. 초기 설정

In [1]:
import torch
from torch.autograd import Variable

torch.manual_seed(777)

## 2. training set과 Variable 만들기

In [2]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

## 3. model 만들기

In [16]:
linear = torch.nn.Linear(4, 3, bias=True)
# version이 0.2 나 0.1.12일 때는 softmax의 parameter인 dim을 정해줘야한다.
softmax = torch.nn.Softmax(dim=1)
model = torch.nn.Sequential(linear, softmax)

## 4. cost function과 optimizer 만들기

In [17]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

## 5. model 훈련시키기

In [18]:
for step in range(2001):
    optimizer.zero_grad()
    
    Y_hat = model(X)
    cost = -Y * torch.log(Y_hat)
    cost = torch.sum(cost, 1).mean()
    cost.backward()
    optimizer.step()
    
    if step % 200 == 0:
        print(step, cost.data.numpy())

0 [ 3.19675446]
200 [ 0.57802826]
400 [ 0.47663793]
600 [ 0.39992741]
800 [ 0.32918203]
1000 [ 0.25765058]
1200 [ 0.224236]
1400 [ 0.20415857]
1600 [ 0.18725973]
1800 [ 0.17284812]
2000 [ 0.16042131]


## 6. model 확인하기

In [19]:
print('--------------')
a = model(Variable(torch.Tensor([[1, 11, 7, 9]])))
print(a.data.numpy(), torch.max(a, 1)[1].data.numpy())

print('--------------')
b = model(Variable(torch.Tensor([[1, 3, 4, 3]])))
print(b.data.numpy(), torch.max(b, 1)[1].data.numpy())

print('--------------')
c = model(Variable(torch.Tensor([[1, 1, 0, 1]])))
print(c.data.numpy(), torch.max(c, 1)[1].data.numpy())

print('--------------')
all = model(Variable(torch.Tensor([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]])))
print(all.data.numpy(), torch.max(all, 1)[1].data.numpy())

--------------
[[  9.26583074e-03   9.90723550e-01   1.06111002e-05]] [1]
--------------
[[ 0.814556    0.16575672  0.01968732]] [0]
--------------
[[  1.80192963e-08   3.86326079e-04   9.99613643e-01]] [2]
--------------
[[  9.26583074e-03   9.90723550e-01   1.06111002e-05]
 [  8.14555824e-01   1.65756837e-01   1.96873490e-02]
 [  1.80192963e-08   3.86326079e-04   9.99613643e-01]] [1 0 2]


In [ ]:
# torch.nn.CrossEntropyLoss 메서드는 LogSoftmax 메서드와 NLLLoss 메서드를 합친 메서드라고 한다.
# LogSoftmax 메서드는 흔히 아는 Softmax 함수에 log를 씌운 함수와 같다.
# NLLLoss 메서드는 Negative log likelihood loss 함수이다.
cost_func = torch.nn.CrossEntropyLoss()