## 1. import 

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

## 2. random seed

In [2]:
torch.manual_seed(777)

## 3. 파일 읽어 들이기, Variable 선언

In [9]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float64)
x_data = xy[:, 0:-1]
y_data = xy[:, -1]

print(x_data.shape, '\n', x_data, '\n', len(x_data), '\n')
print(y_data.shape, '\n', y_data)

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

(25, 3) 
 [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 
 25 

(25,) 
 [ 152.  185.  180.  196.  142.  101.  149.  115.  175.  164.  141.  141.
  184.  152.  148.  192.  147.  183.  177.  159.  177.  175.  175.  149.
  192.]


## 4. hypothesis, cost function, optimizer 만들기 

In [10]:
# 입력하는 feature의 개수는 3개이고, 출력되어야 하는 feature의 개수는 1개이기 때문에 아래와 같이 hypothesis를 만든다.
hypothesis = nn.Linear(3, 1, bias=True)
cost_func = nn.MSELoss()
optimizer = torch.optim.SGD(hypothesis.parameters(), lr=1e-5)

## 5. Model 훈련시키기

In [12]:
for step in range(20001):
    optimizer.zero_grad()
    
    Y_hat = hypothesis(X)
    cost = cost_func(Y_hat, Y)
    cost.backward()
    optimizer.step()
    
    if step % 1000 == 0:
        print(step, "Cost: ", cost.data.numpy(), "\nPrediction:\n", Y_hat.data.numpy())

0 Cost:  [ 1925.97766113] 
Prediction:
 [[ 113.26153564]
 [ 135.59889221]
 [ 133.91279602]
 [ 145.45985413]
 [ 103.59880829]
 [  75.72840881]
 [ 108.46336365]
 [  79.83894348]
 [ 126.13751221]
 [ 115.94333649]
 [ 104.73225403]
 [ 102.88755798]
 [ 138.73216248]
 [ 115.83732605]
 [ 108.84037018]
 [ 137.28636169]
 [ 110.6183548 ]
 [ 130.04876709]
 [ 132.4037323 ]
 [ 118.45792389]
 [ 127.25009155]
 [ 126.87136841]
 [ 121.47673035]
 [ 115.08366394]
 [ 140.79597473]]
1000 Cost:  [ 10.42322922] 
Prediction:
 [[ 153.68367004]
 [ 185.05273438]
 [ 182.14703369]
 [ 198.53987122]
 [ 141.07827759]
 [ 104.30949402]
 [ 148.76824951]
 [ 110.49342346]
 [ 173.22853088]
 [ 160.85296631]
 [ 143.25912476]
 [ 141.47036743]
 [ 188.0171051 ]
 [ 156.07966614]
 [ 149.52127075]
 [ 187.91369629]
 [ 148.54663086]
 [ 178.56420898]
 [ 179.16848755]
 [ 160.30674744]
 [ 174.44351196]
 [ 173.74638367]
 [ 166.24151611]
 [ 154.56245422]
 [ 191.65344238]]
2000 Cost:  [ 8.15367222] 
Prediction:
 [[ 153.28808594]
 [ 185.045

18000 Cost:  [ 6.09765625] 
Prediction:
 [[ 152.93162537]
 [ 184.61367798]
 [ 181.38327026]
 [ 198.8551178 ]
 [ 139.90687561]
 [ 105.25956726]
 [ 150.57191467]
 [ 114.01094818]
 [ 174.32215881]
 [ 164.43608093]
 [ 143.9568634 ]
 [ 142.79994202]
 [ 186.06208801]
 [ 152.84059143]
 [ 151.5287323 ]
 [ 188.51809692]
 [ 144.21183777]
 [ 181.35133362]
 [ 177.05046082]
 [ 158.56724548]
 [ 176.22154236]
 [ 174.42219543]
 [ 167.56985474]
 [ 151.09542847]
 [ 190.58631897]]
19000 Cost:  [ 6.09726143] 
Prediction:
 [[ 152.93417358]
 [ 184.61035156]
 [ 181.3833313 ]
 [ 198.8565979 ]
 [ 139.90124512]
 [ 105.2561264 ]
 [ 150.57635498]
 [ 114.01926422]
 [ 174.31892395]
 [ 164.43515015]
 [ 143.95779419]
 [ 142.79833984]
 [ 186.06079102]
 [ 152.8369751 ]
 [ 151.53234863]
 [ 188.51657104]
 [ 144.20471191]
 [ 181.35934448]
 [ 177.05000305]
 [ 158.56762695]
 [ 176.22563171]
 [ 174.4206543 ]
 [ 167.57388306]
 [ 151.0947876 ]
 [ 190.58340454]]
20000 Cost:  [ 6.09691334] 
Prediction:
 [[ 152.93618774]
 [ 184.6

## 6. Model Test

In [13]:
print("Your score will be", hypothesis(Variable(torch.Tensor([[100, 70, 101]]))).data.numpy())
print("Other scores will be", hypothesis(Variable(torch.Tensor([[60, 70, 110], [90, 100, 80]]))).data.numpy())

Your score will be [[ 186.60018921]]
Other scores will be [[ 182.40029907]
 [ 175.24316406]]
